server.port: 8080

solon.app:
  name: 'vgc-app'
  group: 'vgc'
solon.config.add: "./app.yml,./clients.yml,./channels.yml"
solon.config.load:
  - "clients.yml"
  - "channels.yml"
# 记录器级别的配置示例
solon.logging.logger:
  "root": #默认记录器配置
    level: INFO
api:
  # 每分钟允许的 Http 接口调用数
  query_per_minute_limit: 600